sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 555371
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  alioss:
    access-key-id: LTAI5t6asCvRHARMqNMybDD1
    access-key-secret:
  wechat:
    appid: wx2665bc8e8155ddc6
    secret:
